header:
  version : 14

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url   : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    branch: master
    commit: 97348a2a59f3d451c7b9a4eb116cff9833f6b4dd

  meta-mender:
    url   : "https://github.com/mendersoftware/meta-mender.git"
    branch: kirkstone
    commit: 79e1d551273784bdaf399cf610169a1df8130b08
    layers :
      meta-mender-core:

  poky:
    url   : "https://github.com/yoctoproject/poky.git"
    branch: kirkstone
    commit: db0505b9ba33015038eaecce835fd991db32ed20
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url   : "https://github.com/openembedded/meta-openembedded.git"
    branch: kirkstone
    commit: 7b3fdcdfaab2fc964bbf9eec2cce4e03001fa8cf
    layers :
      meta-oe:
