header:
  version : 14

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url   : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    branch: master
    commit: 97348a2a59f3d451c7b9a4eb116cff9833f6b4dd

  meta-mender:
    url   : "https://github.com/mendersoftware/meta-mender.git"
    branch: kirkstone
    commit: ab941b0b3db96580db54ce0119288deb4c479765
    layers :
      meta-mender-core:

  poky:
    url   : "https://github.com/yoctoproject/poky.git"
    branch: kirkstone
    commit: e9e862752d122945318685ff9eaf6a3090f0f961
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url   : "https://github.com/openembedded/meta-openembedded.git"
    branch: kirkstone
    commit: e42549cef364ae09b3b7c8b64bbeab32e50f1bb0
    layers :
      meta-oe:
