header:
  version : 14

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url   : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    branch: master
    commit: e66e9f734f9b5851166b921572f5d41dbfa5aacb

  meta-mender:
    url   : "https://github.com/mendersoftware/meta-mender.git"
    branch: master-next
    commit: 5fb0af6b89eba96fb5bedaa2d26168233d050d67
    layers :
      meta-mender-core:

  poky:
    url   : "https://git.yoctoproject.org/git/poky"
    branch: mickledore
    commit: 7235399a86b134e57d5eb783d7f1f57ca0439ae5
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url   : "https://github.com/openembedded/meta-openembedded.git"
    branch: mickledore
    commit: f29290563cb821fae95340ba959749641c69ed7f
    layers :
      meta-oe:
