header:
  version : 14

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url   : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    branch: master
    commit: 6588cbf7a18d96fd02183eb81fb309f0ea3fb6af

  meta-mender:
    url   : "https://github.com/mendersoftware/meta-mender.git"
    branch: scarthgap
    commit: 2f70dbad1441055c299332b7ef33dfe1e4f50c1c
    layers :
      meta-mender-core:

  poky:
    url   : "https://git.yoctoproject.org/git/poky"
    branch: scarthgap
    commit: 0b37512fb4b231cc106768e2a7328431009b3b70
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url   : "https://github.com/openembedded/meta-openembedded.git"
    branch: scarthgap
    commit: 1235dd4ed4a57e67683c045ad76b6a0f9e896b45
    layers :
      meta-oe:
