header:
  version : 14
  includes:
    - kas/poky.yml

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url   : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    branch: wrynose
    commit: f94f838863aad1e4be637f6e7f7f3ca411763c14

  meta-mender:
    url   : "https://github.com/mendersoftware/meta-mender.git"
    branch: wrynose
    commit: b68d8c18ca8e15520268478b0eca1ca8ed98a0d6
    layers :
      meta-mender-core:

  meta-openembedded:
    url   : "https://github.com/openembedded/meta-openembedded.git"
    branch: wrynose
    commit: a43f0d532c399458cae44ce66f3799a220fbb497
    layers :
      meta-oe:
