header:
  version : 14

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url   : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    branch: master
    commit: 97348a2a59f3d451c7b9a4eb116cff9833f6b4dd

  meta-mender:
    url   : "https://github.com/mendersoftware/meta-mender.git"
    branch: scarthgap
    commit: f7225aefdb89e5979679925f5a97aa3b17086c2b
    layers :
      meta-mender-core:

  poky:
    url   : "https://git.yoctoproject.org/git/poky"
    branch: scarthgap
    commit: 7d50718f90c51fb7f650c9db59b28c6e0194e5d2
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url   : "https://github.com/openembedded/meta-openembedded.git"
    branch: scarthgap
    commit: 50292b4331431f58a01f5b5518a8645077fc63d6
    layers :
      meta-oe:
