header:
  version : 14

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url   : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    branch: master
    commit: d327090417b56a0357278d98cb2f18c51edda9b1

  meta-mender:
    url   : "https://github.com/mendersoftware/meta-mender.git"
    branch: kirkstone
    commit: f5455b66f259a49d78ca96f0730b57f0f6b3a6a5
    layers :
      meta-mender-core:

  poky:
    url   : "https://git.yoctoproject.org/git/poky"
    branch: kirkstone
    commit: e575d02196b0013c25f8064e4dbe3fc2a0ef72d0
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url   : "https://github.com/openembedded/meta-openembedded.git"
    branch: kirkstone
    commit: 70b217ecc812296d98e1aa027a7d182a8019dded
    layers :
      meta-oe:
