header:
  version : 14

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url   : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    branch: master
    commit: 97348a2a59f3d451c7b9a4eb116cff9833f6b4dd

  meta-mender:
    url   : "https://github.com/mendersoftware/meta-mender.git"
    branch: scarthgap
    commit: 0d393c2267a92091f975eb932338c07109f5f5fd
    layers :
      meta-mender-core:

  poky:
    url   : "https://git.yoctoproject.org/git/poky"
    branch: scarthgap
    commit: e3ce89324da1e33c17c9180ef846f41d92616254
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url   : "https://github.com/openembedded/meta-openembedded.git"
    branch: scarthgap
    commit: e621da947048842109db1b4fd3917a02e0501aa2
    layers :
      meta-oe:
