header:
  version : 14

repos:
  meta-mender-kernel:

  meta-bitbake-variable-substitution:
    url   : "https://github.com/coreycothrum/meta-bitbake-variable-substitution.git"
    branch: master
    commit: e32d92141aec67a6a3ec085c5ad940c9a11d468a

  meta-mender:
    url   : "https://github.com/mendersoftware/meta-mender.git"
    branch: scarthgap
    commit: 2f70dbad1441055c299332b7ef33dfe1e4f50c1c
    layers :
      meta-mender-core:

  poky:
    url   : "https://git.yoctoproject.org/git/poky"
    branch: scarthgap
    commit: 1678bb9ee2a1ce476b5b153d9e79bb9813c33574
    layers :
      meta:
      meta-poky:
      meta-yocto-bsp:

  meta-openembedded:
    url   : "https://github.com/openembedded/meta-openembedded.git"
    branch: scarthgap
    commit: 1235dd4ed4a57e67683c045ad76b6a0f9e896b45
    layers :
      meta-oe:
